import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				{/* Cargar todas las fuentes de equipo desde Google Fonts */}
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
				{/* Script para cargar las fuentes dinámicamente */}
				<Script id="load-team-fonts" strategy="beforeInteractive">
					{`
						(function() {
							const link = document.createElement('link');
							link.rel = 'stylesheet';
							link.href = 'https://fonts.googleapis.com/css2?family=Bebas+Neue:wght@400&family=Teko:wght@600&family=Oswald:wght@600&family=Anton:wght@400&family=Saira+Condensed:wght@700&family=Rajdhani:wght@700&family=Russo+One:wght@400&family=Archivo+Black:wght@400&family=Staatliches:wght@400&family=Exo+2:wght@800&family=Barlow+Condensed:wght@700&family=Kanit:wght@700&display=swap';
							document.head.appendChild(link);
						})();
					`}
				</Script>
			</body>
		</html>
	);
}
